<?php
namespace Mateusz\WebsiteScraper;

use Illuminate\Support\ServiceProvider;

class WebsiteScraperProvider extends ServiceProvider{
    public function boot(){
        $this->publishes([
            __DIR__.'/../config/website_scraper.php' => config_path('website_scraper.php'),
        ]);
    }
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }
}