<?php
namespace Mateusz\WebsiteScraper;

use Illuminate\Support\ServiceProvider;

class WebsiteScraperProvider extends ServiceProvider{
    public function boot(){

    }
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }
}